"""Added name to ticket table

Revision ID: 6d713715ac18
Revises: d8d3c0658591
Create Date: 2025-09-12 03:13:39.510366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d713715ac18'
down_revision: Union[str, None] = 'd8d3c0658591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'name')
    # ### end Alembic commands ###
