version: "3.9"

services:
  edulytica_db:
    container_name: "EdulyticaDatabase"
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5443:5432"

  edulytica_api:
    container_name: "EdulyticaAPI"
    build:
      context: .
      dockerfile: ./src/edulytica_api/Dockerfile
    volumes:
      - ./src/edulytica_api:/app
    ports:
      - "8000:8000"
    depends_on:
      - edulytica_db

  edulytica_frontend:
    container_name: "EdulyticaFrontend"
    build:
      context: ./src/edulytica_api/front_end
      dockerfile: Dockerfile
    volumes:
      - ./src/edulytica_api/front_end:/app
    ports:
      - "3000:3000"
