version: "3.9"

services:
  edulytica_db:
    container_name: "EdulyticaDatabase"
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5443:5432"
    networks:
      - edulytica_network

  edulytica_gateway:
    image: nginx:1.27.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./src/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - edulytica_api
      - edulytica_auth
      - edulytica_llm_models
      - edulytica_orchestration

  edulytica_api:
    container_name: "EdulyticaAPI"
    build:
      context: .
      dockerfile: ./src/edulytica_api/Dockerfile
    volumes:
      - ./src:/app/src
      - ./src/common:/app/src/common
    ports:
      - "8002:8002"
    depends_on:
      - edulytica_db
    env_file:
      - ./.env
    networks:
      - edulytica_network

  edulytica_auth:
    container_name: "EdulyticaAuth"
    build:
      context: .
      dockerfile: ./src/auth/Dockerfile
    volumes:
      - ./src:/app/src
      - ./src/common:/app/src/common
    ports:
      - "8001:8001"
    depends_on:
      - edulytica_db
    env_file:
      - ./.env
    networks:
      - edulytica_network

  edulytica_llm_models:
    container_name: "EdulyticaLLM"
    build:
      context: .
      dockerfile: ./src/models/Dockerfile
    volumes:
      - ./src:/app/src
      - ./src/common:/app/src/common
    ports:
      - "10000:10000"
    depends_on:
      - edulytica_db
    env_file:
      - ./.env
    networks:
      - edulytica_network

  edulytica_orchestration:
    container_name: "EdulyticaOrchestration"
    build:
      context: .
      dockerfile: ./src/orchestration/Dockerfile
    volumes:
      - ./src:/app/src
      - ./src/common:/app/src/common
    ports:
      - "10001:10001"
    depends_on:
      - edulytica_db
    env_file:
      - ./.env
    networks:
      - edulytica_network

  edulytica_frontend:
    container_name: "EdulyticaFrontend"
    build:
      context: ./src/front_end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - edulytica_network
      
  edulytica_chromadb:
    container_name: "EdulyticaChromaDatabase"
    image: "chromadb/chroma:0.6.3"
    volumes:
      - ./chromadb:/chroma/chroma
    ports:
      - "5000:5000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=TRUE
    networks:
      - edulytica_network

networks:
  edulytica_network: