version: '3.8'

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma-db
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - "8080:8080"
    environment:
      - CHROMA_HOST=localhost
      - CHROMA_PORT=8080
    restart: unless-stopped

volumes:
  chroma-data:
    driver: local 