name: Edulytica Workflow

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Copy test environment
        run: cp tests/.test_env .env

      - name: Clear pytest cache
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --cache-clear

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --cov=src -s tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aimclub/Edulytica
