name: Edulytica Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTENV_PATH: tests/.test_env

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5443:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Load .env from file
        run: |
          echo "Loading environment variables from $DOTENV_PATH"
          cat $DOTENV_PATH >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5443 -U $POSTGRES_USER; do sleep 1; done

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --cov=src -s tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aimclub/Edulytica
