name: Edulytica Workflow

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v2
      - name: Print working directory
        run: pwd
      - name: List files in current working directory
        run: |
          current_directory=$(pwd)
          echo "Current working directory: ${current_directory}"
          ls -la "${current_directory}"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
      - name: Install project dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Clear pytest cache
        run: |
          pytest --cache-clear
      - name: Run unittests
        run: |
          pytest --cov=src -s tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aimclub/Edulytica
