name: fix-pep8-command

on:
  repository_dispatch:
    types: [fix-pep8-command]

jobs:
  fix-pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.EDULYTICA_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Generate and set EXCLUDE_PATTERN
        run: |
          EXCLUDE_PATTERN=$(grep -v '^\s*#' .pep8ignore | sed '/^\s*$/d' | sed 's/\r//' | sed 's/^/*/' | sed 's/$/*/' | paste -sd, -)
          echo "EXCLUDE_PATTERN=$EXCLUDE_PATTERN" >> $GITHUB_ENV
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive --exclude=${{ env.EXCLUDE_PATTERN }} .
      - name: Commit autopep8 changes
        id: cap8c
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Automated autopep8 fixes"
          git push
