name: Frontend Build

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./src/front_end
        run: npm install

      - name: Build frontend
        working-directory: ./src/front_end
        run: npm run build
