name: Edulytica_Mypy_Coverage Workflows

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run mypy and generate coverage report
        run: |
          export MYPYPATH=src
          mypy --explicit-package-bases --ignore-missing-imports --html-report mypy_report/ . | tee mypy_output.log

      - name: Upload mypy report
        uses: actions/upload-artifact@v3
        with:
          name: mypy-report
          path: mypy_report/

